### PR TITLE
fix: ProcessPCH++ not parsed and incorrect captured content for processPchCommand

### PR DESCRIPTION
**Pull request by greensky01**

### CODE REVIEW

**Comment by greensky01** [comment]
Hi @thii ,

Please review my fixes. Let me know if you need more info.

**Review by thii — APPROVED** [review]
LGTM. Thanks!

**Comment by thii** [comment]
Can you update the changelog as well? Then I'll push a release.

**Comment by greensky01** [comment]
@thii Updated changelog at: https://github.com/thii/xcbeautify/pull/33

**Pull request merged**
