### PR TITLE
Add GitHub Actions integration

### LINKED ISSUE #17: Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by ealeksandrov**
Resolves https://github.com/thii/xcbeautify/issues/17.

- adds "CI" workflow
  - build release version
  - run tests and pipe output into release version just built
- adds some status badges on Readme 🙂

### CODE REVIEW

**Comment by ealeksandrov** [comment]
It looks like GitHub Actions are disabled in settings for xcbeautify, that's why we can't see test run in PR checks.

**Comment by thii** [comment]
Just enabled it now. Could you try again?

**Review by thii — APPROVED** [review]

**Comment by ealeksandrov** [comment]
Looks good: https://github.com/thii/xcbeautify/runs/1605089931

**Comment by thii** [comment]
I would be nice if the action can build and upload an un released build for every push to the master branch.

**Comment by ealeksandrov** [comment]
Something like nightly dev builds? Where do you want it to be uploaded?
I have a workflow which builds and attaches library to a release when it's published: [deploy.yml](https://github.com/ealeksandrov/EAIntroView/blob/master/.github/workflows/deploy.yml). But it's not on every push, just on every published release.

**Comment by thii** [comment]
We can upload it to the action storage. I've taken a look at it now but it seems like the uploaded files can't be downloaded publicly.

**Pull request merged**
