### PR TITLE
Consolidate Matcher with Regex

### PR DESCRIPTION
**Pull request by cpisciotta**
## Changes

- Remove unnecessary `Matcher` type and consolidate the static `Regex` instances in an extension
- Remove the unnecessary `matcher` suffix from static instance names to avoid type confusion/redundancy
- Mark `Regex.init` as `fileprivate` to prevent unnecessary and expensive `Regex` instantiation

### CODE REVIEW

**Comment by cpisciotta** [comment]
cc: @pepicrft @thii

**Review by pepicrft — APPROVED** [review]

**Comment by pepicrft** [comment]
The merge of [this PR](https://github.com/tuist/xcbeautify/pull/109) caused conflicts here. Do you mind addressing them? We can merge afterward.

**Comment by cpisciotta** [comment]
> The merge of [this PR](https://github.com/tuist/xcbeautify/pull/109) caused conflicts here. Do you mind addressing them? We can merge afterward.

No problem. I'll take a look shortly.

**Comment by cpisciotta** [comment]
@pepicrft Done!

**Comment by pepicrft** [comment]
Merged! 🎉

**Pull request merged**
