### PR TITLE
Linux fixes

### PR DESCRIPTION
**Pull request by Cyberbeni**
https://github.com/Cyberbeni/TypedNotificationCenter/runs/323701075

package tool version update is needed for if swift 5 to work

fixed failed/passed/measured regexes for linux

compile/link/etc. messages still don't work on linux

### CODE REVIEW

**Comment by Cyberbeni** [comment]
#20

**Comment by Cyberbeni** [comment]
Will also delete the swift 4 regexes, they should be kept up to date on a different branch if necessary.

**Comment by Cyberbeni** [comment]
All right, I'm done with the most important regexes, for the rest I think it's best to update the tests first to run xcode/swift builds and expect formatted output to be correct.

**Review by thii — APPROVED** [review]
Thanks!

**Comment by thii** [comment]
@Cyberbeni Could you update the changelog?

**Pull request merged**
